# Generated by Django 5.0.7 on 2024-07-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ru_name", models.CharField(max_length=150, verbose_name="название")),
                (
                    "en_name",
                    models.CharField(
                        max_length=150, verbose_name="английское название"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=4, max_digits=7, verbose_name="широта"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=4, max_digits=7, verbose_name="долгота"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(max_length=100, verbose_name="тайм зона"),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
            },
        ),
    ]
