# Generated by Django 5.0.7 on 2024-07-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="en_name",
            field=models.CharField(
                max_length=150, null=True, verbose_name="английское название"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="timezone",
            field=models.CharField(max_length=100, null=True, verbose_name="тайм зона"),
        ),
    ]
