# Generated by Django 5.0.7 on 2024-07-18 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather_app", "0002_alter_city_en_name_alter_city_timezone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={
                "ordering": ("ru_name",),
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
            },
        ),
        migrations.AlterField(
            model_name="city",
            name="timezone",
            field=models.CharField(max_length=100, null=True, verbose_name="таймзона"),
        ),
        migrations.CreateModel(
            name="RequestHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="Ip address")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время запроса"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="weather_app.city",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "История запросов",
                "verbose_name_plural": "Истории запросов",
                "ordering": ("-created",),
            },
        ),
    ]
