# Generated by Django 5.0.7 on 2024-08-02 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weather_app", "0003_alter_city_options_alter_city_timezone_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RequestHistory",
        ),
    ]
